# Crawl Data X

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = '-'

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,118 kB]
Fetched 2,351 kB in 2s (980 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.16).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:4 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [6,956 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 19.1 kB in 1s (15.4 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
Need to get 31.6 MB of archives.
After this operation, 196 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.13.1-1nodesource1 [31.6 MB]
Fetched 31.6 MB in 1s (60.7 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 121918 files and directories currently installed.)
Preparing to unpack .../nodejs_20.13.1-1nodesource1_amd64.deb ...
Unpacking nodejs (20.13.1-1nodesource1) ...
Setting up nodejs (20.13.1-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.13.1

In [ ]:
# Crawl Data

filename = 'Crypto.csv'
search_keyword = 'Crypto lang:id'
limit = 10

!npx --yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" -l {limit} --token {twitter_auth_token}

Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/UKT.csv, renaming to ./tweets-data/UKT.old.csv

-- Scrolling... (1)
Filling in keywords: UKT lang:id

 (2)

Your tweets saved to: /content/tweets-data/UKT.csv
Total tweets saved: 20
Got 20 tweets, done scrolling...

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

# Check the length of the DataFrame
num_rows = len(df)
print(f"The number of rows in the DataFrame is: {num_rows}")

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1792225011757191261,Sun May 19 16:05:15 +0000 2024,3172,Oh gitu. Januari siapin student loan. Mei naik...,1792225011757191261,NaN,NaN,in,"Michuhol-gu, Republic of Korea",43,120,1037,https://x.com/ardisatriawan/status/17922250117...,170542374,ardisatriawan
1,1792112687956308022,Sun May 19 08:38:55 +0000 2024,921,Ramai UKT Naik Alhamdulillah Muhammadiyah 'Ais...,1792112687956308022,https://pbs.twimg.com/media/GN7bw16awAE2NSK.png,NaN,in,Kota Yogyakarta,22,36,343,https://x.com/bukupembaharu/status/17921126879...,1304372603595837440,bukupembaharu
2,1791792839791456390,Sat May 18 11:27:57 +0000 2024,20165,Jadi gini Karena kenaikan UKT yg terstruktur s...,1791792839791456390,https://pbs.twimg.com/media/GN2516taQAAPuGT.jpg,NaN,in,Jakarta Capital Region,433,178,5734,https://x.com/RidhaIntifadha/status/1791792839...,271922617,RidhaIntifadha
3,1791647219696705903,Sat May 18 01:49:19 +0000 2024,18481,UKT mahal? Tenang kan ada makan siang gratis.....,1791647219696705903,https://pbs.twimg.com/media/GN01poZWwAAD-dt.jpg,NaN,in,NaN,468,201,5181,https://x.com/okkymadasari/status/179164721969...,59823199,okkymadasari
4,1791820598068551976,Sat May 18 13:18:15 +0000 2024,13926,Korban pinjol terbanyak adalah Guru UKT naik g...,1791820598068551976,https://pbs.twimg.com/media/GN3TVpYacAAV21y.jpg,NaN,in,"Dalem Kabagongan, Krg Kedempel",710,1879,2432,https://x.com/RagilSemar/status/17918205980685...,1334070788060631040,RagilSemar
5,1791695268947361823,Sat May 18 05:00:14 +0000 2024,3738,Tenang saja.... Sebentar lagi konflik UKT akan...,1791695268947361823,https://pbs.twimg.com/ext_tw_video_thumb/17916...,NaN,in,"Cengkareng, Indonesia",174,437,1654,https://x.com/NenkMonica/status/17916952689473...,1040306964100669440,NenkMonica
6,1792064286673539435,Sun May 19 05:26:35 +0000 2024,3435,Catat ya: Hiruk-pikuk soal UKT ini nanti ujung...,1792064286673539435,NaN,NaN,in,NaN,114,35,1240,https://x.com/iaridlo/status/1792064286673539435,42561847,iaridlo
7,1791730538371506548,Sat May 18 07:20:23 +0000 2024,16531,Habis nonton RDPU Komisi X DPR RI dg perwakila...,1791730538371506548,https://pbs.twimg.com/media/GN2BayYboAAbpEj.jpg,NaN,in,Jakarta Capital Region,184,124,2355,https://x.com/RidhaIntifadha/status/1791730538...,271922617,RidhaIntifadha
8,1791666384394703320,Sat May 18 03:05:28 +0000 2024,1370,Bu Tjitjik Setditjen Dikti Kemendikbud agar pa...,1791666384394703320,https://pbs.twimg.com/media/GN1HFL9aoAAcBC-.jpg,NaN,in,NaN,21,120,689,https://x.com/msaid_didu/status/17916663843947...,1117990249806721024,msaid_didu
9,1792024179505852868,Sun May 19 02:47:13 +0000 2024,1074,LANGSUNG VIRAL‼️ KALAU ADA RAKYAT YG NGGA BISA...,1792024179505852868,https://pbs.twimg.com/ext_tw_video_thumb/17920...,NaN,in,NaN,11,19,631,https://x.com/Boediantar4/status/1792024179505...,1383750727575605257,Boediantar4
10,1791659377784439257,Sat May 18 02:37:37 +0000 2024,4261,2012: Kita menerapkan sistem UKT untuk menghil...,1791659377784439257,NaN,NaN,in,"Michuhol-gu, Republic of Korea",31,61,1550,https://x.com/ardisatriawan/status/17916593777...,170542374,ardisatriawan
11,1791654769075065073,Sat May 18 02:19:18 +0000 2024,781,Nih yang lagi rame. Belum selesai jadi bahan o...,1791654769075065073,https://pbs.twimg.com/amplify_video_thumb/1791...,NaN,in,NaN,28,60,416,https://x.com/NarasiNewsroom/status/1791654769...,1158355819512991747,NarasiNewsroom
12,1791792839791456390,Sat May 18 11:31:17 +0000 2024,923,Perwakilan BEM Universitas Jenderal Soedirman ...,1791793678341857335,https://pbs.twimg.com/ext_tw_video_thumb/17917...,RidhaIntifadha,in,Jakarta Capital Region,56,20,155,https://x.com/RidhaIntifadha/status/1791793678...,271922617,RidhaIntifadha
13,1791625377686942049,Sat May 18 00:22:31 +0000 2024,2070,Di konoha orang miskin tidak boleh kuliah poko...,1791625377686942049,https://pbs.twimg.com/ext_tw_video_thumb/17916...,NaN,in,"Planeta Rica, Colombia",45,98,1140,https://x.com/5teV3n_Pe9eL/status/179162537768...,224431376,5teV3n_Pe9eL
14,1792319080218972564,Sun May 19 22:19:03 +0000 2024,18,Ketika mimpi anak bangsa dipatahkan dg tinggin...,1792319080218972564,https://pbs.twimg.com/ext_tw_video_thumb/17923...,NaN,in,di hatimu yank👩‍❤️‍👨💍,0,3,9,https://x.com/AiraNtieReal/status/179231908021...,1428002673815482369,AiraNtieReal
15,1791792839791456390,Sat May 18 11:47:08 +0000 2024,727,Perwakilan BEM Universitas Sebelas Maret Surak...,1791797666957123692,https://pbs.twimg.com/ext_tw_video_thumb/17917...,RidhaIntifadha,in,Jakarta Capital Region,87,5,118,https://x.com/RidhaIntifadha/status/1791797666...,271922617,RidhaIntifadha
16,1791698403707212228,Sat May 18 05:12:42 +0000 2024,3337,Liat gaji tenaga pendidik yg rendah dan UKT yg...,1791698403707212228,NaN,NaN,in,NaN,25,18,1246,https://x.com/prkdlx/status/1791698403707212228,1207946570630488066,prkdlx
17,1791821806908882958,Sat May 18 13:23:03 +0000 2024,213,Diprotes mahasiswa karena biaya UKT naiknya ke...,1791821806908882958,https://pbs.twimg.com/media/GN3Ubt7a8AAp5Eb.jpg,NaN,in,NaN,21,28,136,https://x.com/NarasiNewsroom/status/1791821806...,1158355819512991747,NarasiNewsroom
18,1791624312707018992,Sat May 18 00:18:17 +0000 2024,2005,Pertalite mau dihapus UKT naik 500% Pinjol mer...,1791624312707018992,NaN,NaN,in,Jakarta Capital Region,65,23,631,https://x.com/dosenkesmas/status/1791624312707...,318274209,dosenkesmas
19,1791853464165007707,Sat May 18 15:28:51 +0000 2024,310,Karya - Sadar Diri Semoga yang sedang kesulita...,1791853464165007707,https://pbs.twimg.com/media/GN3xOlSakAANeCd.jpg,NaN,in,Indonesia,8,1,61,https://x.com/literarybase/status/179185346416...,1023569652994080769,literarybase

The number of rows in the DataFrame is: 20